server:
  port: 8081
  servlet:
    context-path: /app

logging:
  level:
    root: info
    i2f.secure.**.mapper: debug


spring:
  mvc:
    servlet:
      filter:
        chain:
          patterns: /**
          filters: secureTransferFilter
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: Asia/Shanghai


