server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liteflow_db?useAffectedRows=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml,classpath:/i2f/liteflow/**/mapper/xml/*Mapper.xml,classpath:/i2f/liteflow/**/dao/xml/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    root: info
    i2f.liteflow.**.mapper: debug

